### ISSUE TITLE
`interaction.client` is typed as `discord.Client` and not our own `Client extends discord.Client`

### ISSUE THREAD

**Issue by rob-3** [KnightHacks/dispatch#12]
I ran into this issue while trying to build a nicer button API, but this is an issue that impacts other development as well.

Basically, even though `interaction.client` will be an instance of our own `Client`, TypeScript doesn't recognize it as such. As a result, it is impossible for commands to access any special methods on our `Client` via `interaction.client` that aren't present on `discord.Client` due to type errors.

I have a couple of solutions to this, none of which I really like.

1) We can redefine all of the `Interaction` types to include our client, cast to our own type in `Client.ts`, and force commands to import the types from us instead of `discord.js`. The main drawback is that this is confusing because there are 2 versions of the same type. However, I was able to get this to work.

2) We could try to fork `discord.js` and substitute our own version of `Client`. This is a terrible solution; we shouldn't do this.

3) We can force commands to cast the `interaction.client` themselves. This should always be safe, but I still don't like this at all. I place a high value on making things as easy as possible for command authors, and requiring esoteric casts just to get access to certain functions seems like a poor experience for them.

4) We can write methods to `Client` as free functions with an additional argument of `client: discord.Client` and then substitute `client` for `this` everywhere. I don't hate this, but it does bring up some problems for stateful functions, which no longer have access to our `Client` without even more arguments or casting.

5) We could pass our `Client` or some other object into `run()` like so: `run(interaction: Interaction, client: Client)`. This isn't so bad, but now `interaction.client` is mostly just useless.

6) We could recommend that consumers of `dispatch` create their own mechanism to get access to `Client`, probably some kind of global state/singleton pattern. I don't really like this because it is more work for users, and global state isn't my favored solution.

These are all the solutions I could think of to this problem. I think 5 is the best solution, and 4 also seems ok to me, but I'm interested to hear what y'all think.

**Comment by suneettipirneni** [comment]
We can take a page from other libraries and pass it in via the constructor:

I think a better setup would be to convert `Command` to a class and have it's constructor take our client type:

```ts
class Command {
  // Where the client type is our client type.
  constructor(public client: Client) {}
}
```

Then it can be accessed easily:
```ts
this.client;
```

This would also easily support, an addition like `StorageProvider`

**Comment by rob-3** [comment]
I'm not opposed to this, but 5 is basically an analogous solution. Instead of passing things like `Client` and `StorageProvider` into a constructor, we can just pass them into `run()`. We could also pass in an object to enable consumers to just destructure off what they need like so:
```typescript
const Cmd: Command = {
  name: "hello",
  description: "some description",
  async run({ interaction, storage }) {
    // code
  }
}
```
